Cwarren5701/xp points to multichoice questions
CaptainCoderOrg/IntroToCSharpSite pull request #31
Opened 2022-08-04 18:11 UTC by cwarren5701

Fixed the bug and added a box for to display the XP to be rewarded.

2022-08-04 18:22 UTC, jcollard requested changes
Looks good. Just need to take out the one comment.

2022-08-04 18:22 UTC, jcollard commented on IntroToCSharp/Shared/Components/Activities/MultipleChoiceQuestion.razor
> +        // We had to move this line above so that the submit method can know when the user clicked "show answer" and then award xp accordingly.
No need to put this comment here.

2022-08-04 18:28 UTC, cwarren5701 commented on IntroToCSharp/Shared/Components/Activities/MultipleChoiceQuestion.razor
> +        // We had to move this line above so that the submit method can know when the user clicked "show answer" and then award xp accordingly.
done

2022-08-04 18:43 UTC, jcollard commented
@josht77 @cwarren5701 there is a merge conflict. You'll need to merge develop into the branch to resolve it.

2022-08-07 12:33 UTC, jcollard commented on IntroToCSharpSite.code-workspace
> +}
This file should not be added. You should either delete it locally or add it to .gitignore.

2022-08-07 12:34 UTC, jcollard commented on IntroToCSharp/Shared/Components/Activities/MultipleChoiceQuestion.razor
> +    private int attempts = 0;
private fields should start with an underscore.

2022-08-07 12:35 UTC, jcollard commented on IntroToCSharp/Shared/Components/Activities/MultipleChoiceQuestion.razor
> +    private string XPDisplayStyle = $"color: {Themes.s_CSharpTheme.Palette.Success.ToString()};";
Private fields should start with an underscore.

2022-08-07 12:38 UTC, jcollard requested changes
A few naming things. See: https://www.c-sharpcorner.com/UploadFile/8a67c0/C-Sharp-coding-standards-and-naming-conventions/

2022-08-09 15:17 UTC, jcollard approved these changes
lgtm

2022-08-09 15:18 UTC, merged